services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: caddy-cloudflare
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${CONFIG_ROOT}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}

  dashy:
    networks:
      - caddynet
    image: lissy93/dashy
    ports:
      - 4000:8080
    volumes:
      - ${CONFIG_ROOT}/dashy/conf.yml:/app/user-data/conf.yml:ro
      - ${CONFIG_ROOT}/dashy/custom.css:/app/user-data/custom.css:ro
      - ${CONFIG_ROOT}/dashy/icons:/app/public/icons:ro
      - ${CONFIG_ROOT}/dashy/ffslogo.png:/app/public/ffslogo.png:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  caddynet:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
