services:
  omada:
    image: mbentley/omada-controller:latest
#    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "8088:8088"
      - "8043:8043"
      - "29810:29810/udp"
      - "29811:29811/tcp"
      - "29812:29812/tcp"
      - "29813:29813/tcp"
      - "29814:29814/tcp"
    volumes:
      - ${CONFIG_ROOT}/omada/data:/opt/tplink/EAPController/data
      - ${CONFIG_ROOT}/omada/logs:/opt/tplink/EAPController/logs
      - ${CONFIG_ROOT}/omada/work:/opt/tplink/EAPController/work
